### ISSUE TITLE
[BUG] 404 on assets in umbrella project

### ISSUE THREAD

**Issue by lordhumunguz** [aesmail/kaffy#164] opened 2020-10-21 13:18 UTC
**Versions Used**
Kaffy: 0.9.0
Phoenix: 1.5
Elixir: 1.11.1

**What's actually happening?**
Freshly installed Kaffy in an umbrella project and followed the instruction exactly in README.

Perhaps webpack config needs to be updated?

```elixir
# router.ex
use Kaffy.Routes, scope: "/kaffy"

# endpoint.ex
plug Plug.Static,
  at: "/kaffy",
  from: :kaffy,
  gzip: false,
  only: ~w(assets)

# config.exs
config :kaffy,
  otp_app: :app,
  ecto_repo: App.Repo,
  router: AppWeb.Router
```

My webpack config is the default from Phoenix 1.5

```js
const path = require("path")
const glob = require("glob")
const HardSourceWebpackPlugin = require("hard-source-webpack-plugin")
const MiniCssExtractPlugin = require("mini-css-extract-plugin")
const TerserPlugin = require("terser-webpack-plugin")
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin")
const CopyWebpackPlugin = require("copy-webpack-plugin")

module.exports = (env, options) => {
  const devMode = options.mode !== "production"

  return {
    optimization: {
      minimizer: [
        new TerserPlugin({ cache: true, parallel: true, sourceMap: devMode }),
        new OptimizeCSSAssetsPlugin({}),
      ],
    },
    entry: {
      app: glob.sync("./vendor/**/*.js").concat(["./js/app.js"]),
    },
    output: {
      filename: "[name].js",
      path: path.resolve(__dirname, "../priv/static/js"),
      publicPath: "/js/",
    },
    devtool: devMode ? "eval-cheap-module-source-map" : undefined,
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
          },
        },
        {
          test: /\.[s]?css$/,
          use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"],
        },
      ],
    },
    plugins: [
      new MiniCssExtractPlugin({ filename: "../css/app.css" }),
      new CopyWebpackPlugin([{ from: "static/", to: "../" }]),
    ].concat(devMode ? [new HardSourceWebpackPlugin()] : []),
  }
}
```

**What should happen instead?**
The admin dashboard should render properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/2062592/96724840-433fe500-137e-11eb-9c84-4f986767fe42.png)

**Comment by deepcut** [comment] 2020-10-21 16:49
__UPDATE__

Now I'm seeing 500 for assets caused by `:erlang.binary_to_existing_atom("assets", :utf8)`. I have no custom `resource` config, just the default config provided in README.

```
[error] #PID<0.805.0> running AppWeb.Endpoint (connection #PID<0.775.0>, stream id 6) terminated
Server: localhost:4000 (http)
Request: GET /kaffy/assets/js/dashboard.js
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.binary_to_existing_atom("assets", :utf8)
        (kaffy 0.9.0) lib/kaffy/utils.ex:339: Kaffy.Utils.convert_to_atom/1
        (kaffy 0.9.0) lib/kaffy/utils.ex:335: Kaffy.Utils.convert_to_atoms/2
        (kaffy 0.9.0) lib/kaffy/utils.ex:194: Kaffy.Utils.get_resource/3
        (kaffy 0.9.0) lib/kaffy_web/controllers/resource_controller.ex:92: KaffyWeb.ResourceController.show/2
        (kaffy 0.9.0) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.action/2
        (kaffy 0.9.0) lib/kaffy_web/controllers/resource_controller.ex:1: KaffyWeb.ResourceController.phoenix_controller_pipeline/2
        (phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
```

See screenshot:

![image](https://user-images.githubusercontent.com/2062592/96751916-c91e5900-139b-11eb-93bd-77b509e7a4eb.png)

**Comment by aesmail** [comment] 2020-10-22 06:52
Hey @deepcut 
Could you change your routes

from:
```elixir
use Kaffy.Routes, scope: "/kaffy"
```
to
```elixir
use Kaffy.Routes, scope: "/admin"
```

and see if it works?

**Comment by deepcut** [comment] 2020-10-22 12:39
Hi @aesmail thanks for responding. Still no luck:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/2062592/96872849-24a32200-1442-11eb-9dcd-095b4344d81c.png">

**Comment by aesmail** [comment] 2020-10-22 13:32
I'm not sure if this is related to the umbrella setup or not. But anyway, I'll investigate deeper and will let you know if I find the issue.

**Comment by deepcut** [comment] 2020-10-24 12:52
@aesmail wanted to check in and see if you found anything with umbrella apps. Thanks again!

**Comment by filipecabaco** [comment] 2020-10-28 20:34
I had a similar issue but was able to fix it by moving kaffy static to the top of my `endpoint.ex` file. My suspicion is that `Plug.static` with the `/` in the `at:` option makes this an issue but wasn't able to confirm yet.

**Comment by deepcut** [comment] 2020-11-02 06:57
Thanks @filipecabaco, that indeed did work!

**Comment by filipecabaco** [comment] 2020-11-08 22:43
Maybe the "fix" for this could be an update in the documentation. Does that sound good @aesmail ?

**Comment by aesmail** [comment] 2022-08-11 08:08
I still can't confirm that to be honest. It's working for me whether kaffy static was at the bottom or at the top.
I'll close this issue for now and if anything comes up feel free to re-open it.

**Closed by aesmail** 2022-08-11 08:08 UTC
Labels: bug
