### ISSUE TITLE
[BUG] Livedemo isn't working

### ISSUE THREAD

**Issue by andyduong1920** [aesmail/kaffy#209] opened 2021-07-30 03:53 UTC
Hi there, thanks for creating a nicely Admin UI, just a small issue, the live demo isn't working now ;) 

![image](https://user-images.githubusercontent.com/11751745/127597620-69222d99-bdc6-4dff-b9aa-f3198c90c4c8.png)

**Comment by colindensem** [comment] 2021-09-10 09:58
Duplicate of https://github.com/aesmail/kaffy/issues/189

**Closed** 2021-11-03 10:03 UTC
Labels: bug
