### ISSUE TITLE
Field permission: editing an existing element vs create new element

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#38] opened 2020-05-23 14:43 UTC
Imagine the scenario when you want to allow a field to be created but not edited.
If you use something like:
```elixir
def form_fields(_) do
    [
      username: %{permission: :read},
...
```

Then the field cannot be introduced when you create the resource.

Is there a way to tackle this problem or should we consider introducing different permission mechanism:
```elixir
:permission - can be :editable, :read-only or :create-only
```

**Comment by aesmail** [comment] 2020-05-23 15:13
This is a valid point.
I like your proposed solution.
We have 4 potential scenarios for editing fields:

- Can be edited in both create and update forms. We could use `:write` which is the default now.
- Can be edited only in create form. We could use `:create`.
- Can be edited only in update form. We could use `:update`.
- Cannot be edited at all. We could use `:read`.

Thoughts?

**Comment by areski** [comment] 2020-05-23 18:21
To remove cognitive weight, what would you think in making the permission a list:

For example:
```elixir
username: %{permission: [:read, :create, :update]},
```
Could also consider renaming `permission` by something different, eg. `action` or `display` or something else.

**Comment by aesmail** [comment] 2020-05-23 18:54
> username: %{display: [:read, :create, :update]}
How would this be translated?

A list might be a bit more "verbose" for my taste. I don't mind being more explicit, but in this case I feel it's a bit unnecessary since some values are conflicting or maybe confusing (for example, what would `[:read, :update]` mean?)

I feel, since most fields are expected to be visible and editable by default, a user should tell kaffy when this is not the desired behavior, which leaves a maximum of 3 options to choose from. These options are, by design, not "combinable".

Not sure whether `:permission` or `:display` or something else is suitable in this case. Thinking about it now, I would like the ability to display certain fields on create and maybe a different set of fields on update, which `:display` might communicate that better than `:permission`. However, I'm not sure of the format for the values.

**Comment by areski** [comment] 2020-05-23 20:06
I didn't think this one through well... just sharing my thoughts, hold with me :)

Yes totally agree, a field should be display everywhere by default, and IF it's configured otherwise it will take the new behaviour.

You described well the 4 scenarios but I feel there is cognitive weights in remembering what is what with the actual terms, personally I feel that `read` / `write` are more used for IO.

- Editable on create -> `:add_editable`
- Not Editable on create -> `:add_readonly`
- Editable on update -> `:update_editable`
- Not Editable on update -> `:update_readonly`

Then when you set a field you will have something like:
```elixir
def form_fields(_) do
    [
      username: %{permission: [:add_editable, :update_readonly]},
    ]
```

If you don't want the field to be at all editable, or we could introduce an extra `readonly` that will be like add+update readly, eg:
```elixir
def form_fields(_) do
    [
      username: %{permission: [:add_readonly, :update_readonly]},
or 
      username: %{permission: [:readonly]},
    ]
```

**Comment by aesmail** [comment] 2020-05-24 06:14
Alright. I think we're getting somewhere.
I'd like to propose the following solution:
A `:permissions` option with the following possible values:
`[:create_readonly, :create_editable, :create_hide, :update_readonly, :update_editable, :update_hide]`.
The default should be `[:create_editable, :update_editable]`. I'm going with `:create_*` instead of `:add_*` to stay aligned with phoenix terms. If a `*_hide` value is present, it takes precedence.

An example:

```elixir
def form_fields(_) do
  [
    # once you create a username, you can see it but you cannot change it
    username: %{permissions: [:update_readonly]},
    # email field only visible after creating a record.
    email: %{permissions: [:create_hide]},
    # display terms_agreement field only when creating a record.
    terms_agreement: %{permissions: [:update_hide]},
  ]
end
```

**Comment by areski** [comment] 2020-05-24 13:44
I'm new to Phoenix so be patient with me, I will say a lot of stupidity :)
You are right, it make sense to use `create` for the reason you mentioned.

I forgot the case where you might want to display a field on create but hide it on edit or the reverse, well thought! 

I feel that we are complicating too much, and there is perhaps a more simpler approach to reach the goal... easy to learn and to use.

Thinking loudly here :), 
if we replace `permission` term by 2 terms, eg `create_permission` / `update_permission`,
or even still tempted to replace permission by view :)
```elixir
def form_fields(_) do
  [
    # once you create a username, you can see it but you cannot change it
    username: %{update_permission: :readonly},
    # email field only visible after creating a record.
    email: %{create_permission: :hidden},
    # display terms_agreement field only when creating a record.
    terms_agreement: %{update_permission: :hidden},
  ]
end
```
Using `_view` instead of `permission`.

```elixir
def form_fields(_) do
  [
    # once you create a username, you can see it but you cannot change it
    username: %{update_view: :readonly},
    # email field only visible after creating a record.
    email: %{create_view: :hidden},
    # display terms_agreement field only when creating a record.
    terms_agreement: %{update_view: :hidden},

   # api_key not mentioned when creating, but display as read only when we edit
    api_key: %{create_view: :hidden, update_view: :readonly},
   ]
end

accepted values for create/update_view are :readonly, :hidden, :editable
:editable being the default
```

Thoughts?

**Comment by aesmail** [comment] 2020-05-24 14:25
I like this. It's simple and clear.
I would suggest a minor change to the terms.
Instead of `:create_view` and `:update_view`, we could simply use `:create` and `:update`.

```elixir
def form_fields(_) do
  [
    username: %{update: :readonly},
    email: %{create: :hidden},
    terms_agreement: %{update: :hidden},
    api_key: %{create: :hidden, update: :readonly},
   ]
end
```

**Comment by aesmail** [comment] 2020-05-24 17:38
I created a few milestones just to organize and prioritize the current issues since they're becoming a handful. I assigned this for the next release. No due date though so we can work on features as we see fit time-wise.

**Comment by areski** [comment] 2020-05-24 18:31
Thanks for that!

**Closed** 2020-05-26 03:44 UTC
Labels: enhancement
