### ISSUE TITLE
[FEATURE-REQUEST] Smarter inflector for plural forms

### ISSUE THREAD

**Issue by katafrakt** [aesmail/kaffy#232] opened 2022-06-08 08:38 UTC
**Describe the problem you're proposing to solve**

Right now Kaffy just appends `s` to the word in an attempt to create a plural form. This is good for starters, but creates a lot of incorrect plural forms, even for word commonly used as schema names (company, policy, person...)

**Describe the solution you'd like**

I would like to see (and possibly implement) a bit smarter inflector, which would cover wider set of cases. There is a nice list of rules [here](https://www.grammarly.com/blog/plural-nouns/). We'd just have to figure out what to do with the rules with a lot of exceptions (I'd be happy to discuss possible approaches).

**Describe alternatives you've considered**

There is a package called [inflectorex](https://github.com/girishramnani/inflector) that does just that and implements quite a variety of cases. Problem is - it didn't see any updates in 5 years (I don't know if it's because it's complete or because it's abandoned). Perhaps this could somehow be made an optional dependency to Kaffy.

An interesting thing in this package is that it uses ETS to cache the inflected forms, but I'm not sure it's desirable.

Alternatively, since the package is licensed on MIT, perhaps a large part of it could be just pulled into Kaffy, without reinventing the wheel.

**Comment by aesmail** [comment] 2022-06-08 10:46
It's worth mentioning that Kaffy has the [plural_name](https://github.com/aesmail/kaffy/blob/418893961c67ec77559f9efd90f58c656f051389/lib/kaffy/resource_admin.ex#L283) admin function to customize the plural form of any schema.

Having said that, I think Kaffy could be smarter in dealing with plural names out of the box.

> Alternatively, since the package is licensed on MIT, perhaps a large part of it could be just pulled into Kaffy, without reinventing the wheel.

This would be my preference if we're going that route.

Please feel free to submit a PR for this 🙏🏻.

Maybe we should also consider more options and use cases.

**Comment by aesmail** [comment] 2022-06-08 11:30
[inflex](https://github.com/nurugger07/inflex) seems to be the most popular and still maintained.

I'm still not sure whether it's a good idea to bring an additional dependency just so we can have better support for inflections.

Still up for discussion though.

**Comment by katafrakt** [comment] 2022-06-08 16:22
Oh, didn't know about `inflex`. Nice. However, I too think that pulling it as a dependency would be too much. As such, I see following options:

### 1. Optional support for `inflex`

With something like:

```elixir
plural = 
  if Code.ensure_loaded?(Inflex) do
    Inflex.pluralize(term)
  else
    fallback_pluralize(term)
  end
```

In my experience, this works, however is very tricky to test both paths - with and without `Inflex` module present.

### 2. Support `inflex` via config

```elixir
config :kaffy, inflector: Inflex

# and then

inflector = Application.get_env(:kaffy, :inflector, Kaffy.Inflector)
inflector.pluralize(term)
```

### 3. Not support it at all, relying on a built-in Kaffy inflector

If Kaffy should have its own inflector, again - two options:
* Pull in something almost complete, like `inflectorex` or `inflex` and have to support this code (not sure if I'm comfortable with that, seems a bit complex)
* Build something much simpler, incomplete by design, but still covering much more cases that just appending `s`.

**Comment by aesmail** [comment] 2022-06-09 18:29
I think we could combine 2 things:

* Support `inflex` via config.
* Build something much simpler, incomplete by design, but still covering much more cases that just appending `s`.

I like the idea of supporting an inflection package via config because this could potentially be beneficial for other languages as well in the future.

**Comment by katafrakt** [comment] 2022-06-09 22:12
Sounds good. I'll try to create a PR soon.

**Comment by aesmail** [comment] 2022-08-11 06:52
Closing this issue as #233 has been merged

**Closed by aesmail** 2022-08-11 06:52 UTC
Labels: enhancement
